import type { Metadata } from 'next'


import MainComponent from './componets/mainComponent/MainComponent'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
    <MainComponent>

      <body >{children}</body>
      </MainComponent>

    </html>
  )
}
