import type { Metadata } from "next";
import "./styles/global.css";
import MainComponent from "./componets/mainComponent/MainComponent";

export const metadata: Metadata = {
  title: "Site de Estudo para React Next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    
    <html lang="pt-br">
      
      <body>
      <MainComponent>
        {children}
      </MainComponent>
        </body>
      
    </html>
    
  );
}
